course = 'Python for Beginners'
print(len(course))
print(course.upper())
print(course)
print(course.lower())
print(course.title())
print(course.find('P'))
print(course.find('O'))
print(course.replace('Beginners','Absolute Beginners'))
print('Python' in course)
print('python' in course)
print('P' in course)